version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:476a1024936901889147f53d2a3d8e71e99d76404972d583825514f5608083dc
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.7-alpine@sha256:ca64e54cde860af09cadd5efa3898e5500824379ffecb8ece159682fecef9229
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"